### ISSUE TITLE
ファビコン作り直す

### ISSUE THREAD

**Issue by mochizuki-pg** [teamLeLabo/LeLabo#447]
ファビコン青のほうがよさげ
あとロゴが決まったから、Lではなく
ロゴマークにしたい

**Comment by Ishikawahiroki** [comment]
あざす！
あ、もう青のLには変更してある！
ただ本番用のコード書いてるから、今はさくらサーバにあるfavicon.icoを読みに言ってます。そのせいでローカルでも黄色。さくらにアップロードしたらちゃんと表示なるはず。

そうだね。ロゴマークにしようか。
（例のサイトでうまいこと縮小うまくいけばいいけど・・w）

**Comment by mochizuki-pg** [comment]
なるほどです！
ロゴにしたいのは、他と被らないようにしたいなぁみたいな感じで書いたんですが
きつかったらそのままにしますか！

**Comment by Ishikawahiroki** [comment]
ロゴ触る機会があったので、ついでにこのイシュー対応。
ちょいちっちゃくて見にくいけど、大きさ的にこれが限界w
