### ISSUE TITLE
検索バーのフォントサイズがトップページと統一されていない

### ISSUE THREAD

**Issue by mochizuki-pg** [teamLeLabo/LeLabo#448]
<img width="416" alt="2019-01-27 14 27 20" src="https://user-images.githubusercontent.com/38402160/51826831-55b4f800-232b-11e9-9a90-9a2ec9566861.png">

全ページ確認して、統一する

**Comment by Ishikawahiroki** [comment]
あざす！
あ、そうこれブーツストラップのせいっす。
イシュー#402と同件かな。これは俺やるー

**Comment by mochizuki-pg** [comment]
ああ、そうですね

**Comment by Ishikawahiroki** [comment]
完了
