### ISSUE TITLE
【全体的に】テキスト文の精査

### ISSUE THREAD

**Issue by Ishikawahiroki** [teamLeLabo/LeLabo#453]
戦略的な部分で、当初と変わってきてるとこもありそうなので、全体的にさっと見てテキスト修正があれば行う。

みんなも、「ここの文章変えた方がよくね？」があれば全然言ってください。

**Comment by mochizuki-pg** [comment]
コメントがSlackに通知されるかテスト

**Comment by Ishikawahiroki** [comment]
石川が全体的に気になった所をテキスト修正しました。

今後どのタイミングでも良いので、なんか気になるとかこっちの方がよくねって箇所があったらいつでもなんでも言ってください。一緒に考えましょー。
