### ISSUE TITLE
授業カードのクリック範囲を広くしたい

### ISSUE THREAD

**Issue by mochizuki-pg** [teamLeLabo/LeLabo#499]

**Comment by mochizuki-pg** [comment]
いまってタイトルしかできない

それ以外をクリックすると画像がスケールされる

**Comment by Ishikawahiroki** [comment]
これ確かに。
・「タイトル」と「授業画像」の部分がクリッカブル
でいいのかな〜。
それとも
・カード全体がクリッカブル
の方がいいのか。スマホの場合もあるしな。
試してみるわ！
