### ISSUE TITLE
地味にここの空欄開けたい

### ISSUE THREAD

**Issue by mochizuki-pg** [teamLeLabo/LeLabo#504]
![スクリーンショット 2019-04-17 12 22 41](https://user-images.githubusercontent.com/38402160/56258757-a4dd1e80-610b-11e9-8dd8-feca51c37ad1.png)

**Comment by Ishikawahiroki** [comment]
これ一瞬だから対応したいけど、
空欄ってどこのこと指してる？
「 | 」この縦棒の前後ってことかな？

コメント全然お手隙で良いっす！

**Comment by mochizuki-pg** [comment]
そうですね

**Comment by Ishikawahiroki** [comment]
完了
