### ISSUE TITLE
授業のシェアリンクってどうなってる？

### ISSUE THREAD

**Issue by mochizuki-pg** [teamLeLabo/LeLabo#505]
ララボLeLabo -勉強以外の家庭教師マーケット https://twitter.com/share?via=in1.com&text=%E3%83%A9%E3%83%A9%E3%83%9CLeLabo%20-%E5%8B%89%E5%BC%B7%E4%BB%A5%E5%A4%96%E3%81%AE%E5%AE%B6%E5%BA%AD%E6%95%99%E5%B8%AB%E3%83%9E%E3%83%BC%E3%82%B1%E3%83%83%E3%83%88 @in1.comさんから

最後の文言含めて
@in1.comさんから？

あとこれ授業ページになるんですか？

**Comment by Ishikawahiroki** [comment]
ツイッターおよびフェイスブックシェアで授業ページにリンクされることは確認しました。
・文言はおかしいので修正する

#473 と同件なので一旦削除します。
