### ISSUE TITLE
PCページでも、チャットボタンが隠れてしまう

### ISSUE THREAD

**Issue by mochizuki-pg** [teamLeLabo/LeLabo#508]
![スクリーンショット 2019-05-14 10 17 20](https://user-images.githubusercontent.com/38402160/57664124-e7721800-7631-11e9-9644-0b77841565a9.png)

たぶん、メッセージプレビューの文字数に依存している

**Comment by Ishikawahiroki** [comment]
このイシューは一旦完了。本日夜に本番アップします。
