### ISSUE TITLE
ここのどれかスポーツに変える

### ISSUE THREAD

**Issue by mochizuki-pg** [teamLeLabo/LeLabo#516]
![スクリーンショット 2019-05-29 10 51 08](https://user-images.githubusercontent.com/38402160/58523540-b41db480-81ff-11e9-99d5-dbdd3aeb0aa8.png)

授業がたくさんあるから
ないです表記よりマシ

取り急ぎスポーツに変える

**Comment by Ishikawahiroki** [comment]
完了
